---
title: "Basic Stats Lab"
date: "`r Sys.Date()`"
author: "Your Name"
output: pdf_document
urlcolor: "blue"
params: 
  solutions: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$solutions, 
                      eval = params$solutions,
                      fig.height = 3, 
                      fig.width  = 6,
                      fig.align  = "center")
ggplot2::theme_set(ggplot2::theme_bw())
```

# Learning Objectives

- Practice setting up hypotheses.
- Practice determining which test to run in which scenario.

# Estate Data

For this lab, we will use the estate data at 
<https://data-science-master.github.io/lectures/data/estate.csv>
described [here](https://data-science-master.github.io/lectures/data.html).

You should always provide evidence in terms of a plot and a statistical test,
having written out your hypotheses. Make sure the assumptions of your inference 
scheme are satisfied.

1. Load in these data and load any libraries you need for this exercise.

2. In 2002 the US average home-sale price was $230,000. Is there any evidence
   that the Midwestern city had different home-sale prices? 
    
3. Does having an AC unit affect price?

4. In 2002, about 60% of US households had air conditioning. Is the Midwestern
   city different in this respect?
   
5. If you have a pool, are you more likely to have an AC unit?

    
    
    
    
    
    
           
           
        
